include:
  
stages:
  - test


Cypress Test:
  script:
    - whoami
    - pwd
    - locate npm
    - echo ${PATH}
    - which npm
    - ls -lh $(which npm)
    - npm install
    - npm run report:clean
    - npm run test:user
