default:
  image: cypress/browsers:node18.12.0-chrome107

stages:
  - test

Cypress Test:
  script:
    - npm install
    - npm run report:clean
    - npm run test:transfer
    - npm run test:user
    - npm run test:LoginStatus
    - npm run test:auth
    - npm run test:account
    - npm run mochawesome-merge > index.json
    - npm run marge index.json
    - npm run rimraf mochawesome-report index.js
    - npm run mochawesome-merge --reportDir mochawesome-report > mochawesome-report/output.html
    - npm run marge mochawesome-report/output.html

