default:
  image: cypress/browsers:node18.12.0-chrome107

stages:
  - test

Cypress Test:
  script:
    - npm install
    - npm run report:clean
<<<<<<< HEAD
    - npm run e2e
=======
    - npm run test:user
    - npm run report:merge
    - npm run report:mocha
>>>>>>> 643f92141541eba90aa0a48e637437da1be2429e
